name: Terraform

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get_token.outputs.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Format
        id: format
        run: terraform fmt -recursive -diff

      - name: Commit changes
        if: ${{ steps.format.outputs.stdout != '' }}
        run: |
          git config --global user.name "staffbase-actions[bot]"
          git config --global user.email "staffbase-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🚨 Format Terraform files"
          git push

      - name: Fail if format failed
        if: ${{ steps.format.outputs.stdout != '' }}
        run: exit 1
